// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQDpTXe0G02QcRDqpZ4qKzwVgC5-eUdfg',
    appId: '1:328996489325:web:5ab759737e0e02ef375764',
    messagingSenderId: '328996489325',
    projectId: 'alerta-escolar-1e870',
    authDomain: 'alerta-escolar-1e870.firebaseapp.com',
    storageBucket: 'alerta-escolar-1e870.firebasestorage.app',
    measurementId: 'G-BN8GDDETSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL6Ax79bZjPByDE-ypBkCnkU8scG1qNc8',
    appId: '1:328996489325:android:c606bea66610aa1a375764',
    messagingSenderId: '328996489325',
    projectId: 'alerta-escolar-1e870',
    storageBucket: 'alerta-escolar-1e870.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIqg9vacRkeYIvnaCSJ2osW0Nf11-CwGg',
    appId: '1:328996489325:ios:f45e7721ba20c1cd375764',
    messagingSenderId: '328996489325',
    projectId: 'alerta-escolar-1e870',
    storageBucket: 'alerta-escolar-1e870.firebasestorage.app',
    androidClientId: '328996489325-267t2hme8sr0l74tllhsfubtqg69j9jv.apps.googleusercontent.com',
    iosClientId: '328996489325-4p4vhv5psrpnashnuokin3eboej6ulnq.apps.googleusercontent.com',
    iosBundleId: 'com.example.alertaescolarMb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIqg9vacRkeYIvnaCSJ2osW0Nf11-CwGg',
    appId: '1:328996489325:ios:f45e7721ba20c1cd375764',
    messagingSenderId: '328996489325',
    projectId: 'alerta-escolar-1e870',
    storageBucket: 'alerta-escolar-1e870.firebasestorage.app',
    androidClientId: '328996489325-267t2hme8sr0l74tllhsfubtqg69j9jv.apps.googleusercontent.com',
    iosClientId: '328996489325-4p4vhv5psrpnashnuokin3eboej6ulnq.apps.googleusercontent.com',
    iosBundleId: 'com.example.alertaescolarMb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQDpTXe0G02QcRDqpZ4qKzwVgC5-eUdfg',
    appId: '1:328996489325:web:fdb3ec2b89d0100d375764',
    messagingSenderId: '328996489325',
    projectId: 'alerta-escolar-1e870',
    authDomain: 'alerta-escolar-1e870.firebaseapp.com',
    storageBucket: 'alerta-escolar-1e870.firebasestorage.app',
    measurementId: 'G-RKYCG86LG1',
  );

}