// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRLl9Qp2Sw7NwVO7JeIbmMxbNUifpdM6E',
    appId: '1:328996489325:web:5ab759737e0e02ef375764',
    messagingSenderId: '328996489325',
    projectId: 'alerta-escolar-1e870',
    authDomain: 'alerta-escolar-1e870.firebaseapp.com',
    storageBucket: 'alerta-escolar-1e870.firebasestorage.app',
    measurementId: 'G-BN8GDDETSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf97wf-Iv8xhzZx9r2UHPvHFA5sGKPl84',
    appId: '1:328996489325:android:c606bea66610aa1a375764',
    messagingSenderId: '328996489325',
    projectId: 'alerta-escolar-1e870',
    storageBucket: 'alerta-escolar-1e870.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Ngcb5EJfxnGqOCm7N4iuhMyluLi2a3A',
    appId: '1:328996489325:ios:f45e7721ba20c1cd375764',
    messagingSenderId: '328996489325',
    projectId: 'alerta-escolar-1e870',
    storageBucket: 'alerta-escolar-1e870.firebasestorage.app',
    iosBundleId: 'com.example.alertaescolarMb',
  );

}